version: '3.8'

services:
  express:
    build: .
    volumes:
      - ./:/usr/app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
    networks:
      - backend

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - backend

networks:
  backend:

volumes:
  mongodb-data: