name: Dynamic CI for Changed Directories

on:
    push:
        branches:
            - main
jobs:
    check_changes:
        runs-on: ubuntu-latest
        outputs:
            changed_directories: ${{ steps.detect_changes.outputs.changed_directories }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Detect changes
              id: detect_changes
              run: |
                  # Get the base commit for comparison
                  base_commit="${{ github.event.before }}"
                  if [ -z "$base_commit" ]; then
                    # Handle cases where before is empty
                    base_commit=$(git rev-parse HEAD^1)
                  fi
                  
                  # Get a list of changed files
                  changed_files=$(git diff --name-only $base_commit ${{ github.sha }})
                  
                  # Extract top-level directories
                  changed_directories=$(echo "$changed_files" | grep '/' | cut -d/ -f1 | sort -u)
                  
                  # Convert to JSON array
                  changed_directories_json=$(echo "$changed_directories" | jq -R . | jq -s .)
                  
                  
                  # Set output
                  echo "Changed directories: $changed_directories_json"
                  echo "changed_directories=$changed_directories_json" >> "$GITHUB_OUTPUT"

    build_directories:
        runs-on: ubuntu-latest
        needs: check_changes
        strategy:
            matrix:
                directory: ${{ steps.check_changes.outputs.changed_directories }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0  # Fetch all history

            - name: Build ${{ matrix.directory }}
              run: |
                  echo "Running build for ${{ matrix.directory }}"
                  # Add your build steps here for ${{ matrix.directory }}